[theme]
base = "dark"
primaryColor = "#D99036"
backgroundColor = "#0D0F12"
secondaryBackgroundColor = "#15191F"
textColor = "#F2F3F5"
font = "sans serif"
borderColor = "#292F37"
baseRadius = "medium"

[client]
toolbarMode = "minimal"
