[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "CitrusMiSansSemibold"
url = "app/static/fonts/MiSans-Semibold.ttf"
weight = "520"
style = "normal"

[[theme.fontFaces]]
family = "CitrusRoboto"
url = "app/static/fonts/RobotoVariable-Latin.woff2"
weight = "100 900"
style = "normal"
unicodeRange = "U+0000-024F, U+1E00-1EFF, U+2000-206F, U+20A0-20CF, U+2100-214F, U+2190-21FF, U+2200-22FF, U+FB00-FB4F"

[[theme.fontFaces]]
family = "CitrusNotoSansSC"
url = "app/static/fonts/NotoSansSC-VF.ttf"
weight = "100 900"
style = "normal"
unicodeRange = "U+2E80-2FFF, U+3000-303F, U+3040-30FF, U+3100-312F, U+31A0-31BF, U+3400-4DBF, U+4E00-9FFF, U+F900-FAFF, U+FE30-FE4F, U+FF00-FFEF, U+20000-2FA1F"

[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#FCFCFC"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#111111"
font = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
headingFont = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
codeFont = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
baseFontSize = 15
baseFontWeight = 400
headingFontWeights = 600
codeFontWeight = 400
metricValueFontWeight = 500
baseRadius = "10px"
buttonRadius = "10px"
borderColor = "#E9E9EA"
dataframeBorderColor = "#E9E9EA"
dataframeHeaderBackgroundColor = "#F7F7F7"
showWidgetBorder = true
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#F9F9F9"
secondaryBackgroundColor = "#F6F6F7"
textColor = "#111111"
font = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
headingFont = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
codeFont = "CitrusRoboto, CitrusNotoSansSC, CitrusMiSansSemibold, sans-serif"
headingFontWeights = 600
codeFontWeight = 400
